### ISSUE TITLE
Learning How to Work outside of 'my space'

### ISSUE THREAD

**Issue by iteles** [iteles/personal-goals#11]
There are plenty of times that I have to work outside of a space I can call my own and I really struggle to concentrate and be productive.

There are a few main problem areas:
+ Noise - when noise levels are high, I find it quite hard to focus
+ Lack of things that make the space mine and are my work tools
+ Lack of an external monitor

## Tasks
+ [ ] Make a list of things that make a workspace mine - must-haves and nice-to-haves
+ [ ] Download some good classical music tracks - I use focusatwill but this is not always an option when there is no internet to use it
+ [ ] Make a list of common distractions and solutions to them
+ [ ] Make a list of worktools aside from my computer - must-haves and nice-to-haves
