### ISSUE TITLE
Exercise schedule

### ISSUE THREAD

**Issue by iteles** [iteles/personal-goals#17]
Ever since gyms closed in mid-March meaning that we could no longer go to karate classes 2-3 times a week and we have been in self-quarantine in Gerês, where starting a [couch to 5k](https://www.nhs.uk/live-well/exercise/couch-to-5k-week-by-week/) program is very impractical _and_ the [sprint triathlon we were going to taken part in in June 2020](https://multisport.pt/) was cancelled, I've found getting up the motivation to exercise quite hard.

![image](https://user-images.githubusercontent.com/4185328/79053721-3f950e00-7c37-11ea-80c2-226686aebee3.png)

Sport has never been a part of my routine, but the only way I'll engage in it regularly is:
+ If it is a non-negotiable (x times a week on x days) which _cannot_ be moved from its scheduled time (or I'll find every excuse not to do it)
+ If I _minimally_ enjoy it
  + There has to be some measure of possibility here, it can't _all_ be out of reach from day one
+ If the exercises themselves are very structured, i.e. I know in advance of a group of sessions exactly what I'll be doing not only in _that_ session but also in a number of sessions after that (i.e. the path ahead is clear, like an x week programme) - this is why couch to 5k was successful for me
+ Not take longer than 30 minutes because otherwise it becomes a serious barrier to starting 🤦‍♀️ 

There are a few things I would like to work on:
+ Core strength (yet to determine the measure of this)
+ Back strength (yet to determine the measure of this)
+ Arm strength (go from zero to 20 full push-ups - not the on-your-knees kind!)

## Tasks
+ [ ] Have a little root around youtube to see what looks enjoyable and which programs are available
+ [ ] Make a list of the various options 
+ [ ] Determine the schedule (which days for which exercises)
+ [ ] Get going!

**Comment by iteles** [comment]
Will have to come back to this
