### ISSUE TITLE
Pre-2016 email and to-do list clear out

### ISSUE THREAD

**Issue by iteles** [iteles/personal-goals#2]
- [x] Put on out of office
- [x] Sort out email folder structure
- [ ] Clear out mailbox backlog [before it dies](http://www.techinsider.io/dropbox-is-shutting-down-mailbox-2015-12)!
- [ ] Clear out the ridiculous backlog in email for the new year including 'snoozed' items lost in the ether
- [ ] Clear out the even more ridiculous backlog in to-do lists
- [ ] Shut down all accounts that are unnecessary
- [ ] Another round of unsubscribing from rubbish

Link to https://github.com/dwyl/hq/issues/38

**Comment by iteles** [comment]
😳
