### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by iteles** [iteles/personal-goals#9]
I do a _whole_ lotta admin, which...
![image](https://user-images.githubusercontent.com/4185328/49685892-3f857b00-fae4-11e8-815d-df4941fc3478.png)

Admin for businesses, admin for our flat in London, admin for the construction of https://github.com/dwyl/home, admin for our personal finances, admin for wherever we happen to be staying, admin for [Landim](https://mosteirodelandim.com/).

All of this crap needs to be automated or outsourced. 

As much as I think I'm doing things efficiently, I'm not.

This is a location to log every time I'm doing admin over the next month so a list can be compiled.

## Tasks
+ [ ] Compile list of admin tasks
+ [ ] Determine which can be automated
+ [ ] Get scripts (or whatever is needed) up & running for automation
+ [ ] Determine which can be outsourced
+ [ ] Write up briefs for outsourcing
+ [ ] Find VAs for outsourcing
+ [ ] Trial outsourcing

**Comment by iteles** [comment]
+ Reviewing admin PRs like https://github.com/dwyl/process-handbook/pull/137
+ Tracking parcels arriving at the different addresses in Portugal and which ones have not yet arrived
